#!/bin/sh
set -ex

dir=$(mktemp -d dist-docs.XXXXXX)
trap 'rm -r "$dir"' EXIT

# assumes cabal 2.4 or later
cabal haddock --builddir="$dir" --haddock-for-hackage --enable-documentation

cabal upload --documentation $@ $dir/*-docs.tar.gz